"""add metadata columns to audit logs

Revision ID: 30f501c4aa43
Revises: 4fe9da6bfe6b
Create Date: 2026-06-20 13:15:00.637988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f501c4aa43'
down_revision: Union[str, Sequence[str], None] = '4fe9da6bfe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('override_delta', sa.Float(), nullable=True))
    op.add_column('audit_logs', sa.Column('guardrail_hit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'guardrail_hit')
    op.drop_column('audit_logs', 'override_delta')
    op.drop_column('audit_logs', 'mode')
    # ### end Alembic commands ###
