"""add stop_loss take_profit to trade_proposals

Revision ID: 77619c5ff37d
Revises: 85d6a132c8b0
Create Date: 2026-06-18 12:25:11.721432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77619c5ff37d'
down_revision: Union[str, Sequence[str], None] = '85d6a132c8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_proposals', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('trade_proposals', sa.Column('take_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_proposals', 'take_profit')
    op.drop_column('trade_proposals', 'stop_loss')
    # ### end Alembic commands ###
