"""add stop_loss take_profit to trade_proposals

Revision ID: a93f0848b5cd
Revises: 77619c5ff37d
Create Date: 2026-06-18 12:32:44.198741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93f0848b5cd'
down_revision: Union[str, Sequence[str], None] = '77619c5ff37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
