"""add stop_loss take_profit to trade_proposals

Revision ID: b19f9dc6e324
Revises: a93f0848b5cd
Create Date: 2026-06-19 14:12:43.976840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19f9dc6e324'
down_revision: Union[str, Sequence[str], None] = 'a93f0848b5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
